apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
  namespace: kafka
spec:
  partitions: 3
  replicas: 1
  config:
    #retention.ms: 7200000      # 2시간
    retention.ms: 86400000      # 24시간
    segment.bytes: 1073741824   # 1GB
